# Generated by Django 6.0.6 on 2026-07-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('deleted_at', models.CharField(max_length=50)),
            ],
        ),
    ]
