# Generated by Django 6.0.6 on 2026-07-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingcenter',
            name='roll_number_prefix',
            field=models.CharField(default='STU', max_length=10),
        ),
    ]
