# Generated by Django 6.0.6 on 2026-07-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coachingcenter_roll_number_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingcenter',
            name='logo',
            field=models.CharField(blank=True, db_column='logo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coachingcenter',
            name='id',
            field=models.AutoField(db_column='tuition_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coachingcenter',
            name='name',
            field=models.CharField(db_column='coaching_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='coachingcenter',
            name='roll_number_prefix',
            field=models.CharField(db_column='coaching_short_code', default='STU', max_length=10),
        ),
        migrations.AlterModelTable(
            name='coachingcenter',
            table='tuition',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(db_column='teacher_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('subject', models.CharField(db_column='subject', max_length=255)),
                ('phone', models.CharField(db_column='phone', max_length=50)),
                ('qualification', models.CharField(db_column='qualification', max_length=255)),
                ('experience', models.CharField(db_column='experience', max_length=50)),
                ('status', models.CharField(db_column='status', default='Active', max_length=50)),
                ('coaching_center', models.ForeignKey(db_column='tuition_id', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='users.coachingcenter')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
