# Generated by Django 6.0.6 on 2026-07-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timetable_teacher'),
        ('students', '0004_student_joining_date_student_parent_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
        migrations.RemoveField(
            model_name='exammark',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='exammark',
            name='percentage',
        ),
        migrations.AddField(
            model_name='batch',
            name='multiple_subjects',
            field=models.CharField(db_column='multiple_subjects', default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='batch',
            name='total_students',
            field=models.IntegerField(db_column='total_students', default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.CharField(db_column='exam_date', default='2026-07-09', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_marks',
            field=models.IntegerField(db_column='passing_marks', default=33),
        ),
        migrations.AddField(
            model_name='exam',
            name='standard',
            field=models.CharField(blank=True, db_column='standard', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(blank=True, db_column='subject', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='test_name',
            field=models.CharField(db_column='test_name', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(db_column='total_marks', default=100),
        ),
        migrations.AddField(
            model_name='exammark',
            name='attendance',
            field=models.BooleanField(db_column='attendance', default=True),
        ),
        migrations.AddField(
            model_name='exammark',
            name='obtained_marks',
            field=models.FloatField(blank=True, db_column='obtained_marks', default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.AutoField(db_column='batch_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(db_column='batch_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(db_column='batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.batch'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(db_column='exam_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='exam',
            field=models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='core.exam'),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='id',
            field=models.AutoField(db_column='exam_mark_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='students.student'),
        ),
        migrations.AlterModelTable(
            name='batch',
            table='batch',
        ),
        migrations.AlterModelTable(
            name='exam',
            table='exam',
        ),
        migrations.AlterModelTable(
            name='exammark',
            table='exam_marks',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
