# Generated by Django 6.0.6 on 2026-07-09 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_batch_schedule_remove_batch_subject_and_more'),
        ('students', '0004_student_joining_date_student_parent_contact_and_more'),
        ('users', '0003_coachingcenter_logo_alter_coachingcenter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, db_column='address', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, db_column='batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_list', to='core.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='first_name', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='coaching_center',
            field=models.ForeignKey(db_column='tuition_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.coachingcenter'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(blank=True, db_column='dob', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(db_column='gender', default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.CharField(blank=True, db_column='joining_date', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(blank=True, db_column='parent_contact', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_contact',
            field=models.CharField(blank=True, db_column='student_contact', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_column='student_id', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, db_column='surname', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
