# Generated by Django 6.0.6 on 2026-07-08 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.CharField(db_index=True, max_length=50)),
                ('due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='paid', max_length=50)),
                ('payment_method', models.CharField(default='UPI', max_length=50)),
                ('receipt_id', models.CharField(max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
